export{ default as Navbar} from './Navbar'
export{default as Home} from './Home'
export{default as About} from './About'
export{default as Contact} from './Contact'
export{default as Footer} from './Footer/Footer'
export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as Ocean101} from './HotelList/Ocean101'
export {default as Hotel} from './HotelList/Hotel'
export {default as Standard} from './HotelList/Standard'
export {default as Couple} from './HotelList/Couple'
export {default as Standard3} from './HotelList/Standard3'
export {default as Hillside} from './HotelList/Hillside'
export {default as Hillstandard} from './HotelList/Hillstandard'
export {default as Honeymonn} from './HotelList/Honeymoon'
export {default as Hillpremium} from './HotelList/Hillpremium'
export {default as Maya} from './HotelList/Maya'
export {default as Mayastandard} from './HotelList/Mayastandard' 
export {default as Mayadouble} from './HotelList/Mayadouble'
export {default as Mayapremium} from './HotelList/Mayapremium'
export {default as Checkout} from './Checkout'
export {default as ChatBotComponent} from './ChatbotComponent'